sudo: required
language: cpp

git:
  submodules: true
  depth: 5

jobs:
  include:
    - os: linux
      name: Linux Bionic
      dist: bionic
      script:
        - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
        - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
        - travis_retry wget --no-check-certificate https://cmake.org/files/v3.16/cmake-3.16.0-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.16.0-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.16.0-Linux-x86_64 cmake-install
        - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - cmake --build . --target discpp
    - os: windows
      name: Windows
      install:
        - choco upgrade cmake.install -y
        - choco install make openssl -y
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release .. -G "Unix Makefiles"
        - cmake --build . --target discpp
