language: bash

sudo: required

#services:
#- docker

os:
  - linux
  - windows

# Set the linux distribution to one with updated compilers
dist: bionic

compiler:
- clang

script:
- git clone https://github.com/Microsoft/vcpkg.git
- cd vcpkg
- ./bootstrap-vcpkg.sh
- ./vcpkg integrate install
- ./vcpkg update
- ./vcpkg install nlohmann-json cpr cpprestsdk cpprestsdk[websockets] boost-serialization
- cd ../
- mkdir build
- cd build
- cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/appveyor/projects/discordpp/vcpkg/scripts/buildsystems/vcpkg.cmake
- make