# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  CCACHE_DIR: $(Pipeline.Workspace)/ccache
  #2020.1
  vcpkgGitRef: 7aebb481085de7387f8a9975652c26f9053f66df
  vcpkgArgs: nlohmann-json cpr cpprestsdk cpprestsdk[websockets] boost-serialization
  vcpkgLocation: '$(Build.SourcesDirectory)/vcpkg'

trigger:
- master
- development

jobs:
  - job: Windows_VS2019_x86
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: Cache@2
      displayName: Cache vcpkg
      inputs:
        key: $(vcpkgArgs) | "$(vcpkgGitRef)"" | "$(Agent.OS)"
        path: '$(vcpkgLocation)'
    - task: run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgDirectory: '$(vcpkgLocation)'
        vcpkgArguments: $(vcpkgArgs) --triplet x86-windows
        vcpkgGitCommitId: $(vcpkgGitRef)
        vcpkgTriplet: 'x86-windows'
        vcpkgGitURL: https://github.com/microsoft/vcpkg.git
    - task: run-cmake@0
      displayName: 'Run CMake with Ninja'
      enabled: true
      inputs:
        cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
        cmakeListsTxtPath: '$(Build.SourcesDirectory)/CMakeLists.txt'
        useVcpkgToolchainFile: true
        vcpkgTriplet: 'x86-windows'
        buildDirectory: '$(Build.ArtifactStagingDirectory)'
        buildWithCMakeArgs: '-- -v'
  - job: Linux_Latest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Cache@2
      displayName: Cache vcpkg
      inputs:
        key: $(vcpkgArgs) | "$(vcpkgGitRef)"" | "$(Agent.OS)"
        path: '$(vcpkgLocation)'
    - task: run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgDirectory: '$(vcpkgLocation)'
        vcpkgArguments: $(vcpkgArgs) --triplet x64-linux
        vcpkgGitCommitId: $(vcpkgGitRef)
        vcpkgTriplet: 'x64-linux'
        vcpkgGitURL: https://github.com/microsoft/vcpkg.git
    - task: run-cmake@0
      displayName: 'Run CMake'
      enabled: true
      inputs:
        cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
        cmakeListsTxtPath: '$(Build.SourcesDirectory)/CMakeLists.txt'
        useVcpkgToolchainFile: true
        vcpkgTriplet: 'x64-linux'
        buildDirectory: '$(Build.ArtifactStagingDirectory)'
        buildWithCMakeArgs: '-- -v'