# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  CCACHE_DIR: $(Pipeline.Workspace)/ccache

trigger:
- master
- development

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    windows:
      imageName: 'windows-2019'

steps:
- bash: |
    sudo apt-get install ccache -y
    echo "##vso[task.prependpath]/usr/libccache"
  displayName: 'Install ccache and update PATH to use linked versions of gcc, cc, etc'
- task: Cache@2
  inputs:
    key: 'ccache | "$(Agent.OS)"'
    path: $(CCACHE_DIR)
  displayName: 'ccache'
- task: Cache@2
  inputs:
    key: 'vcpkg | "$(Agent.OS)"'
    path: 'vcpkg'
- script: |
    git clone https://github.com/Microsoft/vcpkg.git
    cd vcpkg
    ./bootstrap-vcpkg.sh
    ./vcpkg integrate install
    ./vcpkg update
    ./vcpkg install nlohmann-json cpr cpprestsdk cpprestsdk[websockets] boost-serialization
    cd ../
    mkdir build
    cd build
    cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/appveyor/projects/discordpp/vcpkg/scripts/buildsystems/vcpkg.cmake
    make
  displayName: 'Compile'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Compile'