# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- development

jobs:
  - job: Windows_VS2019_x64
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: git submodule update --init --recursive
      displayName: Update submodules.
    - task: CMake@1
      displayName: 'Run CMake with Ninja'
  - job: Linux_Latest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: git submodule update --init --recursive
      displayName: Update submodules.
    - task: CMake@1
      displayName: 'Run CMake'