# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- development

jobs:
  - job: Windows_VS2019_x64
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: git submodule update --recursive --init
      displayName: Recursively checkout submodules
    - task: ChocolateyCommand@0
      inputs:
        command: 'install'
        installPackageId: 'openssl'
        installInstallArgs: '-y'
    - task: run-cmake@0
      inputs:
        cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
        cmakeListsTxtPath: '$(Build.SourcesDirectory)/CMakeLists.txt'
        cmakeGenerator: 'Ninja'
        cmakeBuildType: 'Release'
  - job: Linux_Latest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: git submodule update --recursive --init
      displayName: Recursively checkout submodules
    - task: run-cmake@0
      inputs:
        cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
        cmakeListsTxtPath: '$(Build.SourcesDirectory)/CMakeLists.txt'
        cmakeGenerator: 'Ninja'
        cmakeBuildType: 'Release'