# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- development

jobs:
  - job: Windows_MSVC
    pool:
      vmImage: 'windows-2019'
    steps:
    - script: git submodule update --recursive --init
      displayName: Recursively checkout submodules
    - task: ChocolateyCommand@0
      displayName: Install OpenSSL via Chocolatey
      inputs:
        command: 'install'
        installPackageId: 'openssl'
        installInstallArgs: '-y'
    - task: CMake@1
      displayName: CMake Configure
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl'
    - task: CMake@1
      displayName: CMake Compile
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '--build . --target discpp'
  - job: Windows_Clang__v10_0_0
    pool:
      vmImage: 'windows-2019'
    steps:
      - script: git submodule update --recursive --init
        displayName: Recursively checkout submodules
      - task: ChocolateyCommand@0
        displayName: Install Clang via Chocolatey
        inputs:
          command: 'install'
          installPackageId: 'llvm'
          installInstallArgs: '-y'
      - task: ChocolateyCommand@0
        displayName: Install OpenSSL via Chocolatey
        inputs:
          command: 'install'
          installPackageId: 'openssl'
          installInstallArgs: '-y'
      - task: CMake@1
        displayName: CMake Configure
        inputs:
          workingDirectory: 'build'
          cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang'
      - task: CMake@1
        displayName: CMake Compile
        inputs:
          workingDirectory: 'build'
          cmakeArgs: '--build . --target discpp'
  - job: Linux_GCC_v7_5_0
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - script: git submodule update --recursive --init
        displayName: Recursively checkout submodules
      - task: CMake@1
        displayName: CMake Configure
        inputs:
          workingDirectory: 'build'
          cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"'
      - task: CMake@1
        displayName: CMake Compile
        inputs:
          workingDirectory: 'build'
          cmakeArgs: '--build . --target discpp'
