# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- development

jobs:
  - job: Windows_VS2019_x64
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: git submodule update --recursive --init
      displayName: Recursively checkout submodules
    - task: ChocolateyCommand@0
      inputs:
        command: 'install'
        installPackageId: 'openssl'
        installInstallArgs: '-y'
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"'
    - script: |
        cmake --build . --target discpp
  - job: Linux_Latest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: git submodule update --recursive --init
      displayName: Recursively checkout submodules
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"'
    - script: |
        cd build
        make
